repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: "v16.0.6"
    hooks:
      - id: clang-format
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.0.278"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: "23.7.0"
    hooks:
      - id: black
