#ifndef SEQUENCES_H
#define SEQUENCES_H

static char const good_sequence[] =
    "MLRSLIWKRSQAYSSVVTMSSISQRGNERLLSEVAGSHSRDNKILVLGGNGYVGSHICKE"
    "ALRQGFSVSSLSRSGRSSLHDSWVDDVTWHQGDLLSPDSLKPALEGITSVISCVGGFGSN"
    "SQMVRINGTANINAVKAAAEQGVKRFVYISAADFGVINNLIRGYFEGKRATEAEILDKFG"
    "NRGSVLRPGFIHGTRQVGSIKLPLSLIGAPLEMVLKLLPKEVTKIPVIGPLLIPPVNVKS"
    "VAATAVKAAVDPEFASGVIDVYRILQHGH";

static char const bad_sequence[] =
    "MLRSLIWRSQAYSSVVTMSSISQRGNERLLSEVAGSHSRDNKILVLGNGYVGSHICKE"
    "SQMVRINGTANINAVKAAAEQGVKRFVYISADFGVINNLIRGYFEGKRATEAEILDKF"
    "NRGSVLRPGFIHGTRQVGSIKLPLSLIGAPLMVLKLLPKEVTKIPVIGPLLIPPVNVS"
    "TAATAVKAAVDPEFASGVIDVYRILQHGH";

#endif
