name: 📦 Release h3daemon

on:
  push:
    tags:
      - h3daemon-v*

defaults:
  run:
    working-directory: h3daemon

jobs:
  release:
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/h3daemon

    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build
        run: |
          uv sync --all-extras --dev
          uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: h3daemon/dist
          skip-existing: true
          verbose: true
