name: Release hmmer-py

on:
  push:
    tags:
      - hmmer-py-v*

defaults:
  run:
    working-directory: hmmer-py

env:
  CIBW_PROJECT_REQUIRES_PYTHON: ">=3.9"

jobs:
  make_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: hmmer-py/dist/*.tar.gz

  make_linux_wheels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        run: pipx run cibuildwheel==2.18.0

      - uses: actions/upload-artifact@v3
        with:
          path: hmmer-py/wheelhouse/*.whl

  make_macos_intel_wheels:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        run: pipx run cibuildwheel==2.18.0

      - uses: actions/upload-artifact@v3
        with:
          path: hmmer-py/wheelhouse/*.whl

  make_macos_arm_wheels:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3

      - name: Install autoconf
        run: brew install autoconf

      - name: Build wheels
        run: pipx run cibuildwheel==2.18.0

      - uses: actions/upload-artifact@v3
        with:
          path: hmmer-py/wheelhouse/*.whl

  upload_all:
    needs: [make_linux_wheels, make_macos_intel_wheels, make_macos_arm_wheels, make_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
