name: Test h3result

on:
  push:
    paths:
      - h3result/**
      - .github/workflows/test-h3result.yml

defaults:
  run:
    working-directory: h3result

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        build_type: [Release, Debug]

    steps:
      - uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DUSE_SANITIZER='Address;Undefined'

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ASAN_OPTIONS=allocator_may_return_null=1 ctest -C ${{matrix.build_type}} --rerun-failed --output-on-failure
