name: Test hmmer-tables

on:
  push:
    branches:
      - "**"
    paths:
      - hmmer-tables/**
      - .github/workflows/test-hmmer-tables.yml

defaults:
  run:
    working-directory: hmmer-tables

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: |
          pipx run poetry install
          pipx run poetry run pytest
