name: Test h3client

on:
  push:
    branches:
      - "**"
    paths:
      - h3client/**
      - .github/workflows/test-h3client.yml

defaults:
  run:
    working-directory: h3client

jobs:
  test:
    name: Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    env:
      PREFIX:         ${{github.workspace}}/deps
      C_INCLUDE_PATH: ${{github.workspace}}/deps/include
      LIBRARY_PATH:   ${{github.workspace}}/deps/lib
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:
      - uses: actions/checkout@v4

      - name: clone lite-pack
        run: git clone --depth 1 https://github.com/EBI-Metagenomics/lip.git lip

      - name: build & install lite-pack
        run: cd lip && make && make install

      - name: build & install lite-pack-io
        run: cd lip/ext && make && make install

      - name: build & install h3result
        run: cd ../h3result && make && make install

      - name: make
        run: make

      - name: make check
        run: make check
