name: Test h3result

on:
  push:
    branches:
      - "**"
    paths:
      - h3result/**
      - .github/workflows/test-h3result.yml

defaults:
  run:
    working-directory: h3result

jobs:
  test:
    name: Test on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    env:
      PREFIX:         ${{github.workspace}}/deps
      C_INCLUDE_PATH: ${{github.workspace}}/deps/include
      LIBRARY_PATH:   ${{github.workspace}}/deps/lib
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12]

    steps:
      - uses: actions/checkout@v4

      - name: clone lite-pack
        run: git clone --depth 1 https://github.com/EBI-Metagenomics/lite-pack.git lite-pack

      - name: build & install lite-pack
        run: cd lite-pack && make && make install

      - name: build & install lite-pack-io
        run: cd lite-pack/ext && make && make install

      - name: make
        run: make

      - name: make check
        run: make check
