name: Test hmmer-py

on:
  push:
    branches:
      - "**"
    paths:
      - hmmer-py/**
      - .github/workflows/test-hmmer-py.yml

defaults:
  run:
    working-directory: hmmer-py

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v3

      - name: Install autoconf on macos-14
        if: matrix.os == 'macos-14'
        run: brew install autoconf

      - name: Run tests
        run: |
          pipx run poetry install
          pipx run poetry run pytest
